# Generated by Django 4.1.6 on 2023-04-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='net.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
