# Generated by Django 4.1.6 on 2023-04-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw', '0002_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
