# Generated by Django 4.1.6 on 2023-04-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
