# Generated by Django 4.1.6 on 2023-04-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw', '0003_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='skill',
            field=models.CharField(max_length=50),
        ),
    ]
