# Generated by Django 4.1.6 on 2023-04-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw', '0004_customuser_otp_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
