# Generated by Django 4.1.6 on 2023-04-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw', '0005_service_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, default='net.jpg', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('Carpentery', 'Carpentery'), ('electrician', 'electrician'), ('caterer', 'caterer'), ('plumber', 'plumber'), ('maison', 'maison')], max_length=255),
        ),
    ]
