# Generated by Django 4.1.6 on 2023-04-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw', '0006_remove_service_user_service_img_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, default='net.jpg', null=True, upload_to='service_imgs/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('Carpentery', 'Carpentery'), ('Electrician', 'Electrician'), ('Caterer', 'Caterer'), ('Laundry', 'Laundry'), ('Plumber', 'Plumber'), ('Mason', 'Mason')], max_length=255),
        ),
    ]
